config/routes.rb
Ohmygao::Application.routes.draw do
  devise_for :users

  namespace :admin do
    resources :pages
    resources :users
  end
  match '/aboutomg' => 'pages#about', as: :about
  match '/whatisinside' => 'pages#inside', as: :inside
  match '/whyeatit' => 'pages#why', as: :why
  match '/howtoorder' => 'pages#order', as: :order
  root :to => 'pages#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    @user = (user ||= User.new)
    send(@user.role) if @user.role
    can [:read, :about, :inside, :why, :order], Page
  end

  def admin
    can :manage, :all
  end

  def member
    can [:read, :update], User, :id => @user.id
  end
end

app/models/page.rb
class Page < ActiveRecord::Base
  attr_accessible :content, :name
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  attr_accessible :email, :password, :password_confirmation, :remember_me

  ROLES = %w[admin member]
end

app/controllers/admin/admin_controller.rb
class Admin::AdminController < ApplicationController
  before_filter :is_admin

  def is_admin
    redirect_to root_path unless current_user.has_role?(:admin)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  load_and_authorize_resource :page
  respond_to :html, :js
  before_filter :xhr_req

  def index

  end

  def about

  end

  def inside

  end

  def why

  end

  def order

  end

  private
  def xhr_req
    if request.xhr?
      response.headers["Cache-Control"] = "no-cache, no-store, max-age=0, must-revalidate"
      response.headers["Pragma"] = "no-cache"
      response.headers["Expires"] = "Fri, 01 Jan 1990 00:00:00 GTM"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/pages/_form.html.haml
= form_for @page, :html => { :class => 'form-horizontal' } do |f|
  .control-group
    = f.label :name, :class => 'control-label'
    .controls
      = f.text_field :name, :class => 'text_field'
  .control-group
    = f.label :content, :class => 'control-label'
    .controls
      = f.text_area :content, :class => 'text_area'
  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), admin_pages_path, :class => 'btn'

app/views/admin/pages/edit.html.haml
- model_class = Page
.page-header
  %h1=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human, :default => "Edit #{model_class.model_name.human}")
= render :partial => "form"

app/views/admin/pages/index.html.haml
- model_class = Page
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:name)
      %th= model_class.human_attribute_name(:content)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @pages.each do |page|
      %tr
        %td= link_to page.id, admin_page_path(page)
        %td= page.name
        %td= page.content
        %td=l page.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_admin_page_path(page), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), admin_page_path(page), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_admin_page_path, :class => 'btn btn-primary'

app/views/admin/pages/new.html.haml
- model_class = Page
.page-header
  %h1=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human, :default => "New #{model_class.model_name.human}")
= render :partial => "form"

app/views/admin/pages/show.html.haml
- model_class = Page
.page-header
  %h1=t '.title', :default => model_class.model_name.human

%p
  %strong= model_class.human_attribute_name(:name) + ':'
  %br
  = @page.name
%p
  %strong= model_class.human_attribute_name(:content) + ':'
  %br
  = @page.content

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), admin_pages_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_admin_page_path(@page), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), admin_page_path(@page), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'

app/views/admin/users/_form.html.haml
= form_for @user, :html => { :class => 'form-horizontal' } do |f|
  .control-group
    = f.label :email, :class => 'control-label'
    .controls
      = f.text_field :email, :class => 'text_field'
  .control-group
    = f.label :encrypted_password, :class => 'control-label'
    .controls
      = f.text_field :encrypted_password, :class => 'text_field'
  .control-group
    = f.label :reset_password_token, :class => 'control-label'
    .controls
      = f.text_field :reset_password_token, :class => 'text_field'
  .control-group
    = f.label :reset_password_sent_at, :class => 'control-label'
    .controls
      = f.datetime_select :reset_password_sent_at, :class => 'datetime_select'
  .control-group
    = f.label :remember_created_at, :class => 'control-label'
    .controls
      = f.datetime_select :remember_created_at, :class => 'datetime_select'
  .control-group
    = f.label :sign_in_count, :class => 'control-label'
    .controls
      = f.number_field :sign_in_count, :class => 'number_field'
  .control-group
    = f.label :current_sign_in_at, :class => 'control-label'
    .controls
      = f.datetime_select :current_sign_in_at, :class => 'datetime_select'
  .control-group
    = f.label :last_sign_in_at, :class => 'control-label'
    .controls
      = f.datetime_select :last_sign_in_at, :class => 'datetime_select'
  .control-group
    = f.label :current_sign_in_ip, :class => 'control-label'
    .controls
      = f.text_field :current_sign_in_ip, :class => 'text_field'
  .control-group
    = f.label :last_sign_in_ip, :class => 'control-label'
    .controls
      = f.text_field :last_sign_in_ip, :class => 'text_field'
  .control-group
    = f.label :role, :class => 'control-label'
    .controls
      = f.text_field :role, :class => 'text_field'
  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), admin_users_path, :class => 'btn'

app/views/admin/users/edit.html.haml
- model_class = User
.page-header
  %h1=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human, :default => "Edit #{model_class.model_name.human}")
= render :partial => "form"

app/views/admin/users/index.html.haml
- model_class = User
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:email)
      %th= model_class.human_attribute_name(:encrypted_password)
      %th= model_class.human_attribute_name(:reset_password_token)
      %th= model_class.human_attribute_name(:reset_password_sent_at)
      %th= model_class.human_attribute_name(:remember_created_at)
      %th= model_class.human_attribute_name(:sign_in_count)
      %th= model_class.human_attribute_name(:current_sign_in_at)
      %th= model_class.human_attribute_name(:last_sign_in_at)
      %th= model_class.human_attribute_name(:current_sign_in_ip)
      %th= model_class.human_attribute_name(:last_sign_in_ip)
      %th= model_class.human_attribute_name(:role)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @users.each do |user|
      %tr
        %td= link_to user.id, admin_user_path(user)
        %td= user.email
        %td= user.encrypted_password
        %td= user.reset_password_token
        %td= user.reset_password_sent_at
        %td= user.remember_created_at
        %td= user.sign_in_count
        %td= user.current_sign_in_at
        %td= user.last_sign_in_at
        %td= user.current_sign_in_ip
        %td= user.last_sign_in_ip
        %td= user.role
        %td=l user.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_admin_user_path(user), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), admin_user_path(user), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_admin_user_path, :class => 'btn btn-primary'

app/views/admin/users/new.html.haml
- model_class = User
.page-header
  %h1=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human, :default => "New #{model_class.model_name.human}")
= render :partial => "form"

app/views/admin/users/show.html.haml
- model_class = User
.page-header
  %h1=t '.title', :default => model_class.model_name.human

%p
  %strong= model_class.human_attribute_name(:email) + ':'
  %br
  = @user.email
%p
  %strong= model_class.human_attribute_name(:encrypted_password) + ':'
  %br
  = @user.encrypted_password
%p
  %strong= model_class.human_attribute_name(:reset_password_token) + ':'
  %br
  = @user.reset_password_token
%p
  %strong= model_class.human_attribute_name(:reset_password_sent_at) + ':'
  %br
  = @user.reset_password_sent_at
%p
  %strong= model_class.human_attribute_name(:remember_created_at) + ':'
  %br
  = @user.remember_created_at
%p
  %strong= model_class.human_attribute_name(:sign_in_count) + ':'
  %br
  = @user.sign_in_count
%p
  %strong= model_class.human_attribute_name(:current_sign_in_at) + ':'
  %br
  = @user.current_sign_in_at
%p
  %strong= model_class.human_attribute_name(:last_sign_in_at) + ':'
  %br
  = @user.last_sign_in_at
%p
  %strong= model_class.human_attribute_name(:current_sign_in_ip) + ':'
  %br
  = @user.current_sign_in_ip
%p
  %strong= model_class.human_attribute_name(:last_sign_in_ip) + ':'
  %br
  = @user.last_sign_in_ip
%p
  %strong= model_class.human_attribute_name(:role) + ':'
  %br
  = @user.role

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), admin_users_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_admin_user_path(@user), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), admin_user_path(@user), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %meta(name="google" content="notranslate")
    %meta(http-equiv="Content-language" content="en")
    %title= content_for?(:title) ? yield(:title) : "哦买膏 | Oh My Gao"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "http://html5shim.googlecode.com/svn/trunk/html5.js"
    = stylesheet_link_tag "application", :media => "all"
    %link(href="images/apple-touch-icon-144x144.png" rel="apple-touch-icon-precomposed" sizes="144x144")
    %link(href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon-precomposed" sizes="114x114")
    %link(href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon-precomposed" sizes="72x72")
    %link(href="images/apple-touch-icon.png" rel="apple-touch-icon-precomposed")
    %link(href="images/favicon.ico" rel="shortcut icon")


  %body{class: params[:action] }
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          = link_to image_tag('/omg-logo.gif'), root_path, class: "brand", remote: true
          .container.nav-collapse
            %ul.nav
              %li.nav-about
                .nav-text
                  = link_to about_path, remote: true do
                    About
                    %br
                    %span.larger OMG
                    .chinese.notranslate
                      關於哦買膏
              %li.nav-what
                .nav-text
                  = link_to inside_path, remote: true do
                    What Is
                    %br
                    %span.larger INSIDE?
                    .chinese.notranslate
                      它包含了什麼？

              %li.nav-why
                .nav-text
                  = link_to why_path, remote: true do
                    Why
                    %br
                    %span.larger Eat It?
                    .chinese.notranslate
                      吃龟苓膏的益处

              %li.nav-how
                .nav-text
                  = link_to order_path, remote: true do
                    How Do I
                    %br
                    %span.larger Order?
                    .chinese.notranslate
                      怎麼訂購？
    .container
      .content
        .row
          .span12
            = yield :flash
            .maincontent= yield

      %footer
        %p &copy; 哦買膏 Oh My Gao 2012
    /
      Javascripts
      \==================================================
    / Placed at the end of the document so the pages load faster
    = javascript_include_tag "application"
    = yield :javascript

app/views/pages/404.html.haml
%br
.row-fluid
  .span5
    .hero-unit.ohmyhero
      %h1 404 Error
      %h3= "Page \"#{params[:slug]}\" does not exist!"

app/views/pages/_about.html.haml
.row-fluid
  .span9
    .hero-unit.ohmyhero.about
      .row-fluid
        .span4.about1.abouttext
          %h4
            Quality
            %span &
            Service
          %span.brand Oh My Gao
          Herbal Jelly is a well known chinese dessert. Now, through Oh My Gao, you will be able to order online and have it served right to your doorstep.
        .span4.about2.abouttext
          %h4
            品质
            %span 與
            服務
          %span.brand.chinese 哦買膏
          龜苓膏是個家喻戶皢的健康食品。現在，您可以更方便的通过‘哦买膏’网站购买到它。您订购， 我们把它送到您府上。
          %br
          %br
        .span4.abouthead
          %h1
            .top About
            .bot Oh My Gao
            .chi
              關於
              %span 哦買膏

  .span3

app/views/pages/_index.html.haml
.row-fluid
  .span9
    .hero-unit.ohmyhero.index
      .row-fluid
        .span4.introhead
          %h1
            .top Welcome To
            .bot Oh My Gao
            .chi 歡迎光臨
        .span8
          .row-fluid
            .span6.intro1.introtext
              %h4
                Health
                %span +
                Convenience
              It's no secret that every scoop of Herbal Jelly is a spoonful of health, but
              sometimes having a busy day at work may keep you in the office, making it impossible to
              enjoy your favorite glob of herbal jelly goodness.
              %br
              %br
              In light of this problem,
              %span.brand Oh My Gao
              brings deliciously healthy Herbal Jelly right to your doorstep!
            .span6.intro2.introtext
              %h4
                健康
                %span +
                便利
              雖然龜苓膏是個家喻戶曉的健康食品，我們缺會有時在做工的忙碌中無法享用它。
              %br
              %br
              為了解決這個問題，
              %span.brand.chinese 哦買膏
              會把你喜愛的龜苓膏送到門外。
  .span3

app/views/pages/_inside.html.haml
.row-fluid
  .span3
    .hero-unit.ohmyhero.inside
      .row-fluid
        .span12.insidehead
          %h1
            .top What Is
            .bot Inside?
            .chi-top
              它包含了
            .chi-bot
              什麼?
  .span5
  .span4
    .hero-unit.ohmyhero.inside
      .row-fluid
        .span12.inside1.insidetext
          %b
            Herbal Jelly has long been a traditional health food, it was said that its earliest uses stem from the imperial palance of the Qing dynasty. The key ingredients were the Golden Coin Turtles and Wild Tuckahoe, and these were subsequently mixed with Rehmannia and other various herbs to create what is now known as Herbal Jelly.
          %h3
            龟苓膏是历史悠久的传统药膳，相传最初是清宫中专供皇帝食用的名贵药物。它主要以名贵的鹰嘴龟和土茯苓为原料，再配生地等药物精制而成。
          %br

app/views/pages/about.html.haml
= render 'about'
- content_for :javascript do
  :javascript
    $(document).ready(function(){
      History.pushState({url: document.location.href},document.title,"/aboutomg");
    });

app/views/pages/about.js.erb
$('.maincontent').hide().html('<%= escape_javascript render 'about' %>').fadeIn(1000);
$('body').removeClass('about why order inside index').addClass('<%= params[:action] %>');
<% unless params[:history].present? %>
History.pushState({url: "/aboutomg"}, document.title,"/aboutomg");
<% end %>

app/views/pages/index.js.erb
$('body').animate({'background-position-x':'100%'},1000);
$('.maincontent').hide().html('<%= escape_javascript render 'index' %>').fadeIn(1000);
$('body').removeClass('about why order inside index');
$('body').addClass('<%= params[:action] %>');
<% unless params[:history].present? %>
  History.pushState({url: "/"},"哦买膏 | Oh My Gao","/");
<% end %>

app/views/pages/inside.html.haml
= render 'inside'
- content_for :javascript do
  :javascript
    $(document).ready(function(){
      History.pushState({url: document.location.href},document.title,"/whatisinside");
    });

app/views/pages/inside.js.erb
$('.maincontent').hide().html('<%= escape_javascript render 'inside' %>').fadeIn(1000);
$('body').removeClass('about why order inside index').addClass('<%= params[:action] %>');
<% unless params[:history].present? %>
  History.pushState({url: "/whatisinside"},"哦买膏 | Oh My Gao","/whatisinside");
<% end %>

app/views/pages/order.html.haml
= render 'order'
- content_for :javascript do
  :javascript
    $(document).ready(function(){
      History.pushState({url: document.location.href},document.title,"/howtoorder");
    });

app/views/pages/order.js.erb
$('.maincontent').hide().html('<%= escape_javascript render 'order' %>').fadeIn(1000);
$('body').removeClass('about why order inside index').addClass('<%= params[:action] %>');
<% unless params[:history].present? %>
  History.pushState({url: "/howtoorder"},"哦买膏 | Oh My Gao","/howtoorder");
<% end %>

app/views/pages/why.html.haml
= render 'why'
- content_for :javascript do
  :javascript
    $(document).ready(function(){
      History.pushState({url: document.location.href},document.title,"/whyeatit");
    });

app/views/pages/why.js.erb
$('.maincontent').hide().html('<%= escape_javascript render 'why' %>').fadeIn(1000);
$('body').removeClass('about why order inside index').addClass('<%= params[:action] %>');
<% unless params[:history].present? %>
  History.pushState({url: "/whyeatit"},"哦买膏 | Oh My Gao","/whyeatit");
<% end %>